blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RooVetGit/Roo-Code/discussions/categories/feature-requests
      about: Share and vote on feature requests for AIxCoding Agent
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=bocsoft.aixcoding-agent&ssr=false#review-details
      about: Enjoying AIxCoding Agent? Leave a review here!
